env:
  numEnvs: 128
  envSpacing: 2.0
  maxEpisodeLength: 500
  actionSpeedScale: 20
  enableDebugVis: False

  # for BayesSim experiments
  realParams:
    weights: [ 1.0 ]
    means: [ [
      1.0,  # mass
      10.0, 80.0, 90.0, 20.0, 5.0, 5.0  # dof friction
    ] ]
    stds: [ [
      0.001,  # mass
      0.001, 0.001, 0.001, 0.001, 0.001, 0.001, # dof friction
    ] ]

  plane:
    staticFriction: 1.0
    dynamicFriction: 1.0
    restitution: 0.0

  asset:
    assetRoot: "../../assets"
    assetFileName: "mjcf/balance_bot.xml"

sim:
  dt: 0.01
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 8
    num_velocity_iterations: 0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0

  flex:
    num_inner_iterations: 10
    warm_start: 0.25

bayessim:
  modelClass: 'MDRFF'
  trainTrajs: 10000
  trainTrajLen: 10
  trainUpdates: 10000
  finetuneUpdates: 1000
  trainBatchSize: 1000
  components: 4
  hiddenLayers: [128, 128]
  lr: 1.e-4
  summarizerFxn: 'summary_start'
  collectPolicy: 'policy_ones'
  realEvals: 20
  realTrajs: 1
  realIters: 20
  ftuneRL: False

task:
  randomize: True
  # Note: rigid_shape_properties like thickness, restitution, friction do not
  # have a visible effect with random actions, so randomizing over these would
  # not create immediately visible effects.
  randomization_params:
    # frequency: 1000  # do not set frequency, so that IG can randomize any time
    actor_params:
      ball:
        color: True
        rigid_body_properties:
          mass:
            range: [0.01, 5.0]
            operation: "scaling"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
      bbot:
        color: True
        dof_properties:
          friction:
            range: [0.1, 100.0]
            operation: "additive"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
