env:
  numEnvs: 2048
  envSpacing: 1.5
  episodeLength: 500
  enableDebugVis: False

  # for BayesSim experiments
  realParams:
    weights: [ 1.0 ]
    means: [ [
      0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.8, 0.1, 0.1,  # mass
      1.8, 1.8, 1.8, 1.8, 1.8, 0.2, 0.2, 0.1, 0.1 # dof stiffness
    ] ]
    stds: [ [
      0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001,  # mass
      0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 # dof stiffness
    ] ]

  startPositionNoise: 0.0
  startRotationNoise: 0.0

  numProps: 16
  aggregateMode: 3

  actionScale: 7.5
  dofVelocityScale: 0.1
  distRewardScale: 1.5
  rotRewardScale: 0.5
  aroundHandleRewardScale: 1.0
  openRewardScale: 4.0
  fingerDistRewardScale: 10.0
  actionPenaltyScale: 0.01

  asset:
    assetRoot: "../../assets"
    assetFileNameFranka: "urdf/franka_description/robots/franka_panda.urdf"
    assetFileNameCabinet: "urdf/sektion_cabinet_model/urdf/sektion_cabinet_2.urdf"

sim:
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

  flex:
    num_outer_iterations: 4
    num_inner_iterations: 15
    warm_start: 0.8
    relaxation: 0.75


bayessim:
  modelClass: 'MDNN'
  trainTrajs: 10000
  trainTrajLen: 50
  trainUpdates: 5000
  finetuneUpdates: 1000
  trainBatchSize: 1000
  components: 4
  hiddenLayers: [128, 128]
  lr: 1.e-4
  summarizerFxn: 'summary_corrdiff'
  collectPolicy: 'policy_ones'
  realEvals: 20
  realTrajs: 1
  realIters: 20
  ftuneRL: False


task:
  randomize: True
  # Note: rigid_shape_properties like thickness, restitution, friction do not
  # have a visible effect with random actions, so randomizing over these would
  # not create immediately visible effects.
  randomization_params:
    # frequency: 1000  # do not set frequency, so that IG can randomize any time
    actor_params:
      franka:
        color: True
        rigid_body_properties:
          mass:
            range: [0.01, 1.0]
            operation: "scaling"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
        dof_properties:
          stiffness:
            range: [0.1, 2.0]
            operation: "scaling"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
