env:
  numEnvs: 1024
  envSpacing: 0.75
  episodeLength: 600
  enableDebugVis: False
  aggregateMode: 1

  # for BayesSim experiments
  realParams:
    weights: [ 1.0 ]
    means: [ [
      1.8  # default multiplier for all scalings
    ] ]
    stds: [ [
      0.001,  # default std for all params
    ] ]

  stiffnessScale: 1.0
  forceLimitScale: 1.0
  useRelativeControl: False
  dofSpeedScale: 20.0
  actionsMovingAverage: 1.0
  controlFrequencyInv: 1 # 60 Hz

  startPositionNoise: 0.01
  startRotationNoise: 0.0

  resetPositionNoise: 0.01
  resetRotationNoise: 0.0
  resetDofPosRandomInterval: 0.2
  resetDofVelRandomInterval: 0.0

  distRewardScale: -10.0
  rotRewardScale: 1.0
  rotEps: 0.1
  actionPenaltyScale: -0.0002
  reachGoalBonus: 250
  fallDistance: 0.24
  fallPenalty: 0.0

  objectType: "block" # can be block, egg or pen
  observationType: "full_state" # can be "openai", "full_no_vel", "full", "full_state"
  asymmetric_observations: False
  successTolerance: 0.1
  printNumSuccesses: False
  maxConsecutiveSuccesses: 0

  asset:
    # assetRoot: "../../assets"  # set in the code
    assetFileName: "mjcf/open_ai_assets/hand/shadow_hand.xml"
    assetFileNameBlock: "urdf/objects/cube_multicolor.urdf"
    assetFileNameEgg: "mjcf/open_ai_assets/hand/egg.xml"
    assetFileNamePen: "mjcf/open_ai_assets/hand/pen.xml"

sim:
  substeps: 2
  physx:
    num_threads: 4
    solver_type: 1  # 0: pgs, 1: tgs
    num_position_iterations: 8
    num_velocity_iterations: 0
    contact_offset: 0.002
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
  flex:
    num_outer_iterations: 5
    num_inner_iterations: 20
    warm_start: 0.8
    relaxation: 0.75

bayessim:
  trainTrajs: 50000
  collectPolicy: 'policy_random'
  summarizerFxn: 'summary_start'
  trainTrajLen: 10
  ftune: True
  modelClass: MDNN
  components: 4
  hiddenLayers: [128, 128]
  lr: 1.e-4
  realEvals: 100
  realTrajs: 1
  realIters: 100
  ftuneRL: False

task:
  randomize: True
  randomization_params:
    # frequency: 1000  # do not set frequency, so that IG can randomize any time
    observations:
      range: [0, .002] # range for the white noise
      range_correlated: [0, .001 ] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"   # "constant" is to turn on noise after `schedule_steps` num steps
      schedule_steps: 40000
    actions:
      range: [0., .05]
      range_correlated: [0, .015] # range for correlated noise, refreshed with freq `frequency`
      operation: "additive"
      distribution: "gaussian"
      schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
      schedule_steps: 40000
    sim_params: 
      gravity:
        range: [0, 0.4]
        operation: "additive"
        distribution: "gaussian"
        schedule: "linear"  # "linear" will linearly interpolate between no rand and max rand
        schedule_steps: 40000
    actor_params:
      hand:
        color: True
        tendon_properties:
        #  damping:
        #    range: [0.3, 3.0]
        #    operation: "scaling"
        #    distribution: "uniform"
        #    schedule: "constant"
        #    schedule_steps: 0
          stiffness:
            range: [0, 200.0]
            operation: "additive"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
        #dof_properties:
        #  damping:
        #    range: [0.3, 3.0]
        #    operation: "scaling"
        #    distribution: "uniform"
        #    schedule: "constant"
        #    schedule_steps: 0
        #  stiffness:
        #    range: [0.75, 1.5]
        #    operation: "scaling"
        #    distribution: "uniform"
        #    schedule: "constant"
        #    schedule_steps: 0
        rigid_body_properties:
          mass: 
            range: [0.1, 10]
            operation: "scaling"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
        #rigid_shape_properties:
        #  friction:
        #    num_buckets: 250
        #    range: [0.7, 1.3]
        #    operation: "scaling"
        #    distribution: "uniform"
        #    schedule: "constant"
        #    schedule_steps: 0
      object:
        scale:
          range: [0.5, 2.0]  # [0.95, 1.05]
          operation: "scaling"
          distribution: "uniform"
          schedule: "constant"
          schedule_steps: 0
        rigid_body_properties:
          mass: 
            range: [0.1, 10]
            operation: "scaling"
            distribution: "uniform"
            schedule: "constant"
            schedule_steps: 0
        #rigid_shape_properties:
        #  friction:
        #    num_buckets: 250
        #    range: [0.7, 1.3]
        #    operation: "scaling"
        #    distribution: "uniform"
        #    schedule: "constant"
        #    schedule_steps: 0
